### ISSUE TITLE
Ønsker at svare skal forsvinde når man åbner mikrofon

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-admin#16]
På den alm. statusside i hver sal forsvinder "ønsker at svare" lige så snart man unmuter lytteren.
Det samme skal ske på oversigten på admin siden.

**Comment by michaelkrog** [comment]
Admin oversigten abonnerer ikke længere på events, men er i stedet baseret på en opsummering serverside. Denne opsummering har ikke optælling af ønsker om at svare. Det skyldes at logikken om automatisk at "tage hånden op/ned" udelukkende foregår i klienterne baseret på DTMF-events eller ved timeout specificeret i klienten. (F.eks. tages hånden ned efter 60 sekunder)

Serveren har ikke info nok til at holde styr på det og det er derfor fjernet fra admin brugerfladen.
