### ISSUE TITLE
Number of open microphones viser ikke korrekt

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-admin#21]
En tirsdag aften viser admin siden at der er 27 åbne mikrofoner, mens den gamle admin side viser 0.
Det er også meget usandsynligt at det er 27 åbne.

**Comment by michaelkrog** [comment]
Fixed med https://github.com/DRB-IT/blacktiger/issues/131 & https://github.com/DRB-IT/blacktiger/issues/130
